<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="/public/css/base.css" />
  <link rel="stylesheet" href="/public/css/style.css" />
  <title>男神女神 好欢快</title>
</head>
<body>
  <div class="header">
    <div class="wrapper">
      <div class="content clearfix">
        <div class="search"><input type="" placeholder="搜索女神男神吧"/></div>
        <div class="btn"><button>搜索我的神</button></div>
      </div>
    </div>
  </div>
  
  <div class="body">
    <div class="wrapper">
      <?php echo $this->layout()->content?>
    </div>
  </div>
  
  <div class="footer">
    <div class="wrapper">
      <ul class="menu clearfix">
        <li class="item first"><a href="">关于我</a><span class="sepetor"></span></li>
        <li class="item"><a href="">男神之聚集地</a><span class="sepetor"></span></li>
        <li class="item"><a href="">女神之神圣领域</a><span class="sepetor"></span></li>
        <li class="item"><a href="">外围女</a><span class="sepetor"></span></li>
        <li class="item last"><a href="">街拍美男</a><span class="sepetor"></span></li>
      </ul>
    </div>
  </div>
</body>
</html>