<div class="bg">
  <ul class="items clearfix js-masonry" id="shen-container" data-masonry-options='{ "itemSelector": ".item" }'>
    <?php foreach ($this->shenlist as $index => $shen):?>
        <li class="item item-<?php echo $index %2 == 0 ? "odd": "event"?>">
      <div class="top">
        <?php echo $shen["image"][0]?>
      </div>
      <div class="btm">
        <div class="t1">
          <span class="name"><?php echo $shen["title"]?></span>
          <span class="star">
            10万+ 喜欢
          </span>
        </div>
        <div class="t2">
          <p><?php echo $shen["desc"]?></p>
        </div>
      </div>
    </li>
    <?php endforeach;?>
  </ul>
</div>